AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 instance deployment template'

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small
      - m5.large
  
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment
    AllowedValues:
      - dev
      - staging
      - prod
  
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH Key name for EC2 instance
  
  AMIId:
    Type: String
    Description: AMI ID (if empty, latest Amazon Linux 2 will be used)
    Default: ""

Conditions:
  UseSpecifiedAMI: !Not [!Equals [!Ref AMIId, ""]]

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !If 
        - UseSpecifiedAMI
        - !Ref AMIId
        - !Ref LatestAmiId
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub 'ec2-${Environment}-${AWS::StackName}'
        - Key: Environment
          Value: !Ref Environment
  
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
  PublicIP:
    Description: EC2 Public IP
    Value: !GetAtt EC2Instance.PublicIp
  PublicDNS:
    Description: EC2 Public DNS
    Value: !GetAtt EC2Instance.PublicDnsName
